### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by influx6** [micheloosterhof/docker-cowrie#7]
Currently attempting to run the cowrie instance using the dockerfile built but it fails. Using the following to run a interactive container and manually lunching `cowrie`, still failed with issues regarding python `twisted`.

Commands:

```
> ./build.sh
> docker run -it -p 2222:2222 -p 2223:2223 cowrie /bin/bash
```
Logs:

```
cowrie@e94a57e9ccc2:~/cowrie-git$ ./bin/cowrie start -n
Activating virtualenv "cowrie-env"
Starting cowrie with extra arguments [ ] ...
Traceback (most recent call last):
  File "/cowrie/cowrie-git/cowrie-env/bin/twistd", line 9, in <module>
    load_entry_point('Twisted==17.1.0', 'console_scripts', 'twistd')()
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/cowrie/cowrie-git/twisted/plugins/cowrie_plugin.py", line 161, in makeService
    factory.portal = portal.Portal(core.realm.HoneyPotRealm(cfg))
  File "/cowrie/cowrie-git/cowrie/core/realm.py", line 61, in __init__
    self.pckl = pickle.load(file(cfg.get('honeypot', 'filesystem_file'), 'rb'))
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 792, in get
    d = self._unify_values(section, vars)
  File "/cowrie/cowrie-git/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1162, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'honeypot'
cowrie@e94a57e9ccc2:~/cowrie-git$ 
```

**Comment by lelandlater** [comment]
I receive the same error: ```backports.configparser.NoSectionError: No section: 'honeypot'```.

The issue which references this one says to use Python2.7 instead of Python3. Is this an issue with configparser and Python?
